/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecovehicle;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Owner extends javax.swing.JFrame {

    String Username = LoginPage.user.getText();

    
    public Owner() {
        initComponents();
        ownerSession.setText(Username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logincapital = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        financialData = new javax.swing.JLabel();
        ownerSession = new javax.swing.JLabel();
        checkoutCar = new javax.swing.JLabel();
        premiumPackage = new javax.swing.JLabel();
        customersRating = new javax.swing.JLabel();
        myGarage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(23, 148, 175));

        logincapital.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        logincapital.setForeground(new java.awt.Color(255, 255, 255));
        logincapital.setText("Owner Page");

        logout.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecovehicle/icons/icons8_logout_rounded_left_30px.png"))); // NOI18N
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecovehicle/icons/LogoEcoSmallWhite.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(logo)
                .addGap(50, 50, 50)
                .addComponent(logincapital)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logincapital)
                    .addComponent(logout))
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 100));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        financialData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        financialData.setForeground(new java.awt.Color(23, 148, 175));
        financialData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecovehicle/icons/icons8_financial_growth_analysis_30px.png"))); // NOI18N
        financialData.setText("Financial Data");
        financialData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(23, 148, 175), new java.awt.Color(23, 148, 175), null, null));
        financialData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                financialDataMouseClicked(evt);
            }
        });
        jPanel2.add(financialData, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        ownerSession.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ownerSession.setForeground(new java.awt.Color(23, 148, 175));
        ownerSession.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecovehicle/icons/icons8_landlord_30px.png"))); // NOI18N
        ownerSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ownerSessionMouseClicked(evt);
            }
        });
        jPanel2.add(ownerSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 260, 40));

        checkoutCar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        checkoutCar.setForeground(new java.awt.Color(23, 148, 175));
        checkoutCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecovehicle/icons/icons8_car_dealership_building_30px.png"))); // NOI18N
        checkoutCar.setText("Checkout Car");
        checkoutCar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(23, 148, 175), new java.awt.Color(23, 148, 175), null, null));
        checkoutCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkoutCarMouseClicked(evt);
            }
        });
        jPanel2.add(checkoutCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        premiumPackage.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        premiumPackage.setForeground(new java.awt.Color(23, 148, 175));
        premiumPackage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecovehicle/icons/icons8_best_seller_30px.png"))); // NOI18N
        premiumPackage.setText("Premium Package");
        premiumPackage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(23, 148, 175), new java.awt.Color(23, 148, 175), null, null));
        premiumPackage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                premiumPackageMouseClicked(evt);
            }
        });
        jPanel2.add(premiumPackage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        customersRating.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        customersRating.setForeground(new java.awt.Color(23, 148, 175));
        customersRating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecovehicle/icons/icons8_very_popular_topic_30px.png"))); // NOI18N
        customersRating.setText("Customers Rating");
        customersRating.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(23, 148, 175), new java.awt.Color(23, 148, 175), null, null));
        customersRating.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customersRatingMouseClicked(evt);
            }
        });
        jPanel2.add(customersRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        myGarage.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        myGarage.setForeground(new java.awt.Color(23, 148, 175));
        myGarage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecovehicle/icons/icons8_garage_30px.png"))); // NOI18N
        myGarage.setText("My Garage");
        myGarage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(23, 148, 175), new java.awt.Color(23, 148, 175), null, null));
        myGarage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myGarageMouseClicked(evt);
            }
        });
        jPanel2.add(myGarage, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 850, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        HomePage a = new HomePage();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void financialDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financialDataMouseClicked
        OwnerFinancialData a = new OwnerFinancialData();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_financialDataMouseClicked

    private void ownerSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ownerSessionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerSessionMouseClicked

    private void checkoutCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutCarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_checkoutCarMouseClicked

    private void premiumPackageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_premiumPackageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_premiumPackageMouseClicked

    private void customersRatingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersRatingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_customersRatingMouseClicked

    private void myGarageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myGarageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_myGarageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Owner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkoutCar;
    private javax.swing.JLabel customersRating;
    private javax.swing.JLabel financialData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logincapital;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel myGarage;
    private javax.swing.JLabel ownerSession;
    private javax.swing.JLabel premiumPackage;
    // End of variables declaration//GEN-END:variables
}
